apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/renaneiras/2service.git  # Ajuste com seu repositório
    targetRevision: main
    path: devops
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

